"""add species table, upgrade patients

Revision ID: 136c83bc1294
Revises: c475d960ce5e
Create Date: 2026-02-26 00:00:43.131656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136c83bc1294'
down_revision: Union[str, Sequence[str], None] = 'c475d960ce5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ Создаём таблицу species

    op.create_table(
        "species",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.UniqueConstraint("code", name="uq_species_code"),
    )

    # 2️⃣ Добавляем колонку species_id временно nullable

    op.add_column(
        "patients",
        sa.Column("species_id", sa.BigInteger(), nullable=True),
    )

    # 3️⃣ Добавляем остальные новые поля

    op.add_column(
        "patients",
        sa.Column("sex", sa.String(length=10), nullable=True),
    )

    op.add_column(
        "patients",
        sa.Column("weight", sa.Numeric(5, 2), nullable=True),
    )

    op.add_column(
        "patients",
        sa.Column("microchip_number", sa.String(length=50), nullable=True),
    )

    # 4️⃣ Создаём базовые записи species (минимальный справочник)

    op.execute("""
        INSERT INTO species (code, name)
        VALUES
            ('dog', 'Dog'),
            ('cat', 'Cat'),
            ('unknown', 'Unknown')
        ON CONFLICT (code) DO NOTHING
    """)

    # 5️⃣ Backfill существующих пациентов

    op.execute("""
        UPDATE patients
        SET species_id = (
            SELECT id FROM species WHERE code = 'unknown'
        )
        WHERE species_id IS NULL
    """)

    # 6️⃣ Делаем колонку обязательной

    op.alter_column(
        "patients",
        "species_id",
        nullable=False,
    )

    # 7️⃣ Создаём внешний ключ

    op.create_foreign_key(
        "fk_patients_species",
        "patients",
        "species",
        ["species_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # 8️⃣ Индексы (для производительности)

    op.create_index(
        "ix_patients_species_id",
        "patients",
        ["species_id"],
    )

    op.create_index(
        "ix_patients_microchip_number",
        "patients",
        ["microchip_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'microchip_number')
    op.drop_column('patients', 'weight')
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'species_id')
    op.drop_table('species')
    # ### end Alembic commands ###
