"""add latin_name and active to species

Revision ID: 9e27917b6b76
Revises: 136c83bc1294
Create Date: 2026-02-26 00:37:46.663943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e27917b6b76'
down_revision: Union[str, Sequence[str], None] = '136c83bc1294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'sex',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('patients', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('patients', 'microchip_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index(op.f('ix_patients_microchip_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_species_id'), table_name='patients')
    op.drop_constraint(op.f('fk_patients_species'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'species', ['species_id'], ['id'])
    op.add_column('species', sa.Column('latin_name', sa.String(length=128), nullable=True))
    op.add_column('species', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('species', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('species', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column("species", "active", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('species', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('species', 'code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('species', 'active')
    op.drop_column('species', 'latin_name')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_patients_species'), 'patients', 'species', ['species_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_patients_species_id'), 'patients', ['species_id'], unique=False)
    op.create_index(op.f('ix_patients_microchip_number'), 'patients', ['microchip_number'], unique=True)
    op.alter_column('patients', 'microchip_number',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('patients', 'weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('patients', 'sex',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
